### ISSUE TITLE
link to CORONANET dataset seems broken

### ISSUE THREAD

**Issue by forestier** [complexity-science-hub/ranking_npis#1]
Hi,

The link to [coronanet_release.csv](http://coronanet-project.org/data/coronanet_release.csv) seems broken :

[measureclass.py](https://github.com/complexity-science-hub/ranking_npis/blob/main/LASSO/measureclass.py#L141)

Best regards,

Germain

**Comment by lukasgeyrhofer** [comment]
They changed how they store the database on their homepage. Newest version should work now.
